on:
  push:
    branches:
      - main

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  build-release:
    needs: release-please
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.release_created }}
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.release-please.outputs.tag_name }}
          persist-credentials: false

      - name: Install gettext
        run: sudo apt-get update && sudo apt-get install -y gettext

      - name: Compile translations
        run: ./bin/i18n compile

      - name: Generate plasmoid package
        env:
          TAG_NAME: ${{ needs.release-please.outputs.tag_name }}
        run: |
          cd ./src
          zip -r "../plasmusic-toolbar-${TAG_NAME}.plasmoid" .

      - name: Upload plasmoid package to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ needs.release-please.outputs.tag_name }}
        run: |
          gh release upload "$TAG_NAME" "./plasmusic-toolbar-${TAG_NAME}.plasmoid"